version: '3'
services:
  app:
    image: dialog-system
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - HF_HOME=/app/huggingface_cache
    ports:
      - 8000:80
    command: ["--debug"]
    tty: true